### ISSUE TITLE
How to stop emacs from turning a TAB into 8 SPACES

### ISSUE THREAD

**Issue by limTeTE** [purcell/emacs.d#444] opened 2017-05-26 06:14 UTC
Hi~ I'm new to Emacs, i'd like ask about how to stop Emacs from turning a TAB into 8 SPACES when i use it to write a Makefile, i've tried M-x makefile-mode and it cannot help. So any suggestions, thank you there~

**Comment by YuanPres** [comment] 2017-05-26 10:33
See #429 ……Why are two people experiencing the same problem, But also can not solve ?......
Please show your system environment and software version......

**Comment by limTeTE** [comment] 2017-05-26 10:46
ubuntu14.04, Emacs24.3.1. I solved this by turning off the "whitespace -cleanup-mode"

**Comment by purcell** [comment] 2017-05-27 06:27
> I solved this by turning off the "whitespace -cleanup-mode"

Weird. `whitespace-cleanup-mode` doesn't break Makefile editing for me. Have you customised `whitespace-style`? Have you changed the configuration locally at all? How can I reproduce this starting with a fresh checkout of my configuration?

**Comment by limTeTE** [comment] 2017-05-27 06:38
i don't make any change to the configuration. I just turn up the Emacs and C-x C-f a new file, with M-x makefile-mode, it's good when i just edit the file with TAB, but when i save it with C-x C-s, the TAB just become to 8 whitespces.

**Comment by purcell** [comment] 2017-05-27 07:55
Hmm, I also can't reproduce it using those instructions in Emacs 25.2, at least. Your Emacs is pretty old (March 2013), so you should consider upgrading, and that might help.

**Comment by limTeTE** [comment] 2017-05-27 07:57
Maybe that's the reason, i'll try. Thank you anyway~

**Comment by junjiemars** [comment] 2017-06-26 15:00
```lisp
(setq indent-tabs-mode t)
(setq tab-width 4)
```

@limTeTE

**Comment by purcell** [comment] 2017-06-26 21:14
Closing this because there's no sign it's an issue with this configuration specifically.

**Closed by purcell** 2017-06-26 21:14 UTC
