### ISSUE TITLE
company:frontend company-quickhelp error symbol 

### ISSUE THREAD

**Issue by iwvwi** [purcell/emacs.d#390] opened 2016-10-26 19:15 UTC
When M+X choice anything command ,it show
# "company:frontend company-quickhelp error “Symbol”s function definition is void: pos-tip-hide" on command hide "

How can I deal with this?
Thank!

**Comment by purcell** [comment] 2016-10-30 03:23
Which Emacs version are you using, and on what platform? Are you using it in the terminal? Please provide more information.

**Comment by iwvwi** [comment] 2016-10-30 03:29
Emacs version= 25.1.1
System           =x86_64_centos6.5
Yes is it ,using in interminal.

**Comment by purcell** [comment] 2016-10-30 09:57
Strange. Can you use `M-x find-library` to locate `pos-tip`? The version of `pos-tip` I have is the one from MELPA, and it definitely has `pos-tip-hide`. It's not clear to me how this situation can happen! :-)

**Comment by iwvwi** [comment] 2016-10-30 10:28
#  As its same.
When M+X choice anything command ,it still show"company:frontend company-quickhelp error “Symbol”s function definition is void: pos-tip-hide" on command hide ".

# Perhaps the reson is emacs version too new.

emacs --debug-init show this
**"Debugger entered--Lisp error: (error "Package `git-blame-' is unavailable")
  signal(error ("Package `git-blame-' is unavailable"))
  error("Package `%s-%s' is unavailable" git-blame "")
  package-compute-transaction(nil ((git-blame)))
  package-install(git-blame nil)
  (if (boundp (quote package-selected-packages)) (package-install package nil) (package-install package)) (if (or (assoc package package-archive-contents) no-refresh) (if (boundp (quote package-selected-packages)) (packag$(if (package-installed-p package min-version) t (if (or (assoc package package-archive-contents) no-refresh) (if (b$
  require-package(git-blame nil t)
  (progn (package-refresh-contents) (require-package package min-version t))
  (if (or (assoc package package-archive-contents) no-refresh) (if (boundp (quote package-selected-packages)) "**
#  I really appreciate it.

**Comment by cutexiaoba** [comment] 2016-11-02 22:30
Yes, I have encountered the same issue. Perhaps the emacs version is too new.

**Comment by purcell** [comment] 2016-11-03 07:31
Aha, so the problem was that Emacs was not starting up fully due to the error @iwvwi pasted (thanks!). This was fixed in 7123a31, so updating to the latest version of this config and then restarting Emacs should fix the problem.

**Closed by purcell** 2016-11-03 07:31 UTC

**Comment by lzt1226** [comment] 2016-12-29 11:10
Help, help, I now also appears the question, but with you the latest configuration.I change how to solve.

**Comment by purcell** [comment] 2017-01-15 00:30
@lzt1226 And the problem is exactly the same for you? Can you provide more information please?
