### ISSUE TITLE
Tabs auto-convert to spaces when saving makefile in Opensuse 42

### ISSUE THREAD

**Issue by viscroad** [purcell/emacs.d#429] opened 2017-04-19 15:38 UTC
Hi Sir,
I work in makefile recently using your config under OpenSuse 42, I get the following error when I executing my makefile.

makefile:2: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.

I can insert Tabs when I editing files, but tabs auto convert to spaces when saving. The same config works in Windows but get error under Linux.

**Comment by purcell** [comment] 2017-04-20 10:34
I worked on a `Makefile` today myself and verified that this is not a problem for me. You'd need to provide instructions detailing how to reproduce this from scratch with an empty checkout of this config if I'm to guess at what might be going wrong.

**Comment by viscroad** [comment] 2017-04-22 03:32
I download the latest .emacs.d config, then start up emacs. C-X C-F open a makefile, 

```
test : test.o
        cc -o test test.o

test.o : test.c
        cc -c test.c
```

This is the simple makefile. I can insert tab before cc command, but after C-X C-S save the file, tabs before cc command change to spaces. Open a shell then execute make command, get error

**makefile:2: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop**

**Comment by YuanPre** [comment] 2017-04-22 04:35
I tested it under Arch Linux.The `Makefile` is normal.

I have never used OpenSUSE, but I suspect that the system text encoding or keyboard layout settings.
That is the system by default tab into a space.
I can not provide good advice. But if you don't customized configuration, you can try delete `~/.emacs.d/` and  reinstall this configuration.

**Comment by viscroad** [comment] 2017-04-22 05:36
Thanks!
I have already deleted .emacs.d/ and re-download the from Github, restart emacs, it doesn't work.
After I started emacs -nw -Q in console and tried vim, it worked.

I know, it must be some configuration in my OpenSuse conflict with emacs.d config, but it is werd.

**Comment by YuanPre** [comment] 2017-04-22 05:47
@viscroad That is, it does not load any configuration but can be used……
Have you used any other configuration? Try the other configuration files on GitHub might be better......
Put your system's language and character encoding. This helps solve the problem.

**Comment by purcell** [comment] 2017-04-22 09:09
> I know, it must be some configuration in my OpenSuse conflict with emacs.d config, but it is weird.

What happens if you start Emacs using the `--no-site-file` option? Does it work better then?

**Comment by viscroad** [comment] 2017-04-26 13:11
@YuanPre 
Thanks! Limited accessing Internet these days, ha....

system language: en_US.UTF-8
keyboard layout: layout:     us

**Comment by viscroad** [comment] 2017-04-26 13:12
@purcell 

Sir, sorry for late replying, --no-site-file works the same result, after save makefile, we get spaces instead original tabs... ...

**Comment by YuanPre** [comment] 2017-04-27 00:20
Do you use a GUI or a CLI version?
And Your DE(Desktop Environment)？
Yeah ... now the problem seems to be your character in the preservation of the document was escaped ... ...
Have you tried vim or any other editor? 
And……Tested on my openSUSE Tumbleweed with KDE Plasma.....
It's normal......

**Comment by viscroad** [comment] 2017-04-28 04:47
@yuanyuanpre 

the following sys info. Tried both in GUI and CLI. I also tried in vim, it was fine. emacs -nw -Q was fine. It's weird... ...

```
~> uname -r
4.1.12-1-default
~> lsb_release -a
LSB Version:    core-5.0-amd64:core-5.0-noarch:desktop-5.0-amd64:desktop-5.0-noarch:imaging-5.0-amd64:imaging-5.0-noarch:languages-5.0-amd64:languages-5.0-noarch
Distributor ID: SUSE LINUX
Description:    openSUSE Leap 42.1 (x86_64)
Release:        42.1
Codename:       n/a
~> kde4-config -v
Qt: 4.8.6
KDE Development Platform: 4.14.10
kde4-config: 1.0
~> plasmashell --version
plasmashell 5.4.2


```

**Comment by yuanyuanpre** [comment] 2017-04-28 05:25
Yeah...Your system is like mine, except the kernel. My kernel is manually compiled `linux-4.10.11-x86_64`. The emacs version is `25.2` .
But the Makefile is passed on my system...
Really strange ah...
It seems beyond my ability.
Sorry for I couldn't solve your problem.
I have limited ability of emacs because I use emacs for only two months...

**Comment by viscroad** [comment] 2017-05-05 17:10
@YuanPres 
My Emacs version is 24.3. What differences from us are kernel and Emacs version. I keep eyes on this and try to find the root cause. Whatever, thank you very much!!!  Maybe I will send you email when I fix this issue.
```
GNU Emacs 24.3.1
Copyright (C) 2013 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

```

**Comment by junjiemars** [comment] 2017-06-26 15:02
@viscroad , same with [issue-444](https://github.com/purcell/emacs.d/issues/444)

**Comment by purcell** [comment] 2017-06-26 21:14
Closing this because there's no sign it's an issue with this configuration specifically.

**Closed by purcell** 2017-06-26 21:14 UTC
