### ISSUE TITLE
ivy-alt-done will collide multiple-cursors

### ISSUE THREAD

**Issue by mut0u** [purcell/emacs.d#477] opened 2017-08-09 05:26 UTC
The keybinding of  ivy-alt-done will make the multiple-cursors error.

```
(define-key ivy-minibuffer-map (kbd "RET") #'ivy-alt-done)

```

When use `mc/edit-lines` function , the whole buffer will change the content to **mc/edit-lines**

**Comment by purcell** [comment] 2017-08-13 01:38
Sorry, I don't quite understand what steps I should follow to reproduce this.

**Comment by mut0u** [comment] 2017-08-17 11:05
Oh, sorry.


First of all, the content of my buffer is this

![01](https://user-images.githubusercontent.com/1238353/29409279-1cfb22d4-8311-11e7-8ec9-4eee4596da35.png)

Then , I use `M-x ` to call `mc/edit-lines` function just like image2.

![02](https://user-images.githubusercontent.com/1238353/29409331-4c308d6e-8311-11e7-9d12-458216e92507.png)

At last , the content of the buffer will be changed like this.
![03](https://user-images.githubusercontent.com/1238353/29409388-91c3f85c-8311-11e7-91de-a67faab16564.png)


The origin content will be changed into `mc/edit-lines` string.

I found out that the reason is this configure   `(define-key ivy-minibuffer-map (kbd "RET") #'ivy-alt-done)` .
If I change the binding to another key (not the RET), `mc/edit-lines` will work again.

**Comment by purcell** [comment] 2017-09-02 03:30
Right, I can reproduce this, but it seems like an unfortunate clash between `multiple-cursors` and `ivy` due to one of them (most likely `multiple-cursors`) doing wacky stuff. I'm not going to change the `RET` binding, and `mc/edit-lines` works fine if run with `C-c m c` instead, so I'm just going to close this, sorry.

**Closed by purcell** 2017-09-02 03:30 UTC
