### ISSUE TITLE
projectile configuration make projectile's candidate display error in emacs 29

### ISSUE THREAD

**Issue by knysfh** [purcell/emacs.d#837] opened 2023-02-24 13:13 UTC
Hello!Thanks for you contribution.

The candidate content is displayed incorrectly when i use the `projectile-find-file` function in my project file.If i comment the following content in `init-projectile.el`, it can be displayed normally.
```
  ;; (when (executable-find "rg")
  ;;   (setq-default projectile-generic-command "rg --files --hidden"))
```

before comment
![image](https://user-images.githubusercontent.com/49890449/221186284-1338b60e-35ac-45ac-8483-a81899666836.png)

after
![image](https://user-images.githubusercontent.com/49890449/221185783-e78deaa9-6280-46c8-8cba-5e6eee1ecb40.png)

**Comment by purcell** [comment] 2023-02-24 13:33
Odd, I can't reproduce this. Are you on Windows perhaps? It looks like the line endings in the `rg` output are unexpected.

**Comment by knysfh** [comment] 2023-02-24 15:49
I use arch linux under pure wayland, and I tried emacs28 but the problem persists.I'm not sure if it's a system problem. 

## Expected behavior
Show project files when use `C-c p f`
## Current behavior
All filenames incorrectly displayed on one line.
![image](https://user-images.githubusercontent.com/49890449/221219275-40fcc401-787b-4161-ada1-62c1eea6a0ee.png)

## Steps to reproduce
1. clone this repositorie
2. create the following directory
```
├─example
│  ├─src
│  │  ├─main.py
│  ├─setup.py
│  ├─.projectile
```
3. start emacs and use `C-x C-f` to open setup.py, then use `C-c p f` to search for project files.
## System Information
os: Arch Linux x86_64
kernel: 6.1.12-arch1-1
wm: sway
rg: ripgrep 13.0.0
emacs: 28.2/29.0

**Comment by purcell** [comment] 2023-02-24 17:44
Thanks, those reproduction steps were perfect. I've committed a fix now.

**Closed** 2023-02-24 17:44 UTC
