### ISSUE TITLE
Company autocompletion unpredictable in terminal

### ISSUE THREAD

**Issue by gustavjf** [purcell/emacs.d#377] opened 2016-09-04 15:27 UTC
Emacs version: `25.1.1` (via `brew install --devel emacs`)
Also tried: `24.5.1`, `24.5.1 --with-x`

On a fresh clone, running `M-/`, or `company-complete` fails (no tooltip) with the error message:

`Company: frontend company-quickhelp-frontend error "Symbol's function definition is void: pos-tip-hide" on command hide`.

Company completion is unpredictable - sometimes it works the first time running`company-complete` after opening a buffer, but afterwards it fails and throws the error above consistently. That's until I remove `company-quickhelp` from company frontends.

I suspect this is because `pos-tip` [doesn't work](https://github.com/expez/company-quickhelp/issues/12#issuecomment-183414081) in the terminal.

@purcell Are you using a GUI distribution of Emacs? If you're using it in the terminal and the tooltip with documentation pop-up is working well, I'd be grateful to know how. For the moment I'm relying on F1 to open a separate documentation buffer, which is a bit more cumbersome.

**Comment by purcell** [comment] 2016-09-05 09:17
Hmmm... I normally use a GUI version of Emacs, typically Emacs HEAD.

Do you see the problem when starting Emacs in the terminal, or creating a terminal frame using Emacsclient? I've tried both with my Emacs and can't reproduce this.

**Comment by gustavjf** [comment] 2016-09-06 19:23
Sorry, I should have provided steps to reproduce:

Inside OSX Terminal
Emacs Version: 25.1.1

1. `git clone https://github.com/purcell/emacs.d.git ~/.emacs.d`
2. `emacs`
3. wait for package downloads
4. Load and treat as safe `sanityinc-solarized` theme
5. Lots of compile warnings:

<img width="1280" alt="screen shot 2016-09-06 at 9 05 35 pm" src="https://cloud.githubusercontent.com/assets/3981598/18287035/c8187e88-7475-11e6-92d7-6c342a8f72ac.png">

6. `C-x C-f ~/.emacs.d/lisp/init-company.el`
7. On line 3, type `(set`. Let completion start automatically, can see tooltip.

<img width="1280" alt="screen shot 2016-09-06 at 9 19 45 pm" src="https://cloud.githubusercontent.com/assets/3981598/18287494/ad85a742-7477-11e6-8638-0558fc8c930f.png">


8. *While still seeing the tooltip, `C-f`, then `C-b`. Cursor should now be above automatically inserted closing paren and tooltip should have disappeared.*
9. `M-/` to force completion. Check minibuffer:

<img width="1280" alt="screen shot 2016-09-06 at 9 16 56 pm" src="https://cloud.githubusercontent.com/assets/3981598/18287404/4c51297e-7477-11e6-8c08-08dea1dc52ef.png">

10. Delete line 3, retype `(set`, can't see tooltip show up. `M-/` shows `pos-tip` error again.

**Comment by purcell** [comment] 2017-02-27 09:59
I believe this is now fixed upstream in `company-quickhelp`.

**Closed** 2018-01-27 02:13 UTC
