### ISSUE TITLE
treesit-extra-load-path error when start emacs

### ISSUE THREAD

**Issue by kungelee** [purcell/emacs.d#849] opened 2023-08-15 18:02 UTC
let: Symbol’s value as variable is void: treesit-extra-load-path

**Comment by purcell** [comment] 2023-08-16 08:38
Which Emacs version do you have?

**Comment by purcell** [comment] 2023-08-16 16:14
Maybe the change in 7b174a5d helps?

**Comment by kungelee** [comment] 2023-08-17 00:48
# Warning
 ■  Warning (initialization): An error occurred while loading ‘c:/HOME/.emacs.d/init.el’:

Symbol's value as variable is void: treesit-extra-load-path

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

# Emacs Version
GNU Emacs 29.1 (build 5, x86_64-w64-mingw32) of 2023-08-01

# Sysmtem version
Microsoft Windows [Version 10.0.19045.3324]

Version Windows 10 Enterprise
Version number 22H2
Installation date 2023-03-28 
Operating System Internal Version 19045.3324
Experience Windows Feature Experience Pack 1000.19041.1000.0

**Comment by purcell** [comment] 2023-08-17 05:47
Okay, thanks, and is that with the latest commit? I would hope that it would have fixed the issue for you.

**Comment by kungelee** [comment] 2023-08-17 06:15
> Maybe the change in [7b174a5](https://github.com/purcell/emacs.d/commit/7b174a5d968cbdb1cd66844bb4b4a700b7ef750b) helps?

 ■  Warning (initialization): An error occurred while loading ‘c:/HOME/.emacs.d/init.el’:

End of file during parsing: c:/HOME/.emacs.d/init.el

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

D:\emacs-29.1-src\bin\runemacs.exe --debug-init

**Comment by kungelee** [comment] 2023-08-17 07:08
![01](https://github.com/purcell/emacs.d/assets/30483657/b8c78b32-a4ff-4826-aa64-78595312cac2)
![02](https://github.com/purcell/emacs.d/assets/30483657/299e3a84-dae0-4049-8502-b17191663305)

**Comment by kungelee** [comment] 2023-08-17 07:09
for %i in (*) do ren "%i" "libtree-sitter-%i"

**Comment by kungelee** [comment] 2023-08-17 08:18
# Compile again with: --with-tree-sitter

./autogen.sh
PKG_CONFIG_PATH=/mingw64/lib/pkgconfig ./configure --host=x86_64-w64-mingw32 \
--target=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --with-wide-int \
--with-jpeg --with-xpm --with-png --with-tiff --with-rsvg --with-xml2 \
--with-gnutls --without-imagemagick --with-tree-sitter
make -j
make install prefix=/d/emacs-29.1


![image](https://github.com/purcell/emacs.d/assets/30483657/1cd78aa3-bad2-4990-9f0d-87efaaf77d6c)

**Comment by kungelee** [comment] 2023-08-17 08:45
> 

Thank you very much. I found the problem. I missed a parenthesis when copying the code, but the tree-sitter still does not work. In addition, the hard line on the right does not display properly

![image](https://github.com/purcell/emacs.d/assets/30483657/6461087f-3cd2-4d5f-b08c-8a198b1c7c16)

**Comment by kungelee** [comment] 2023-08-17 08:46
![image](https://github.com/purcell/emacs.d/assets/30483657/f9007a85-185d-4f2b-b0dc-e94c468ddade)

**Comment by purcell** [comment] 2023-08-17 09:27
Okay, but that code in `init.el` isn't the same as the code in my repo.

Re. the line on the right, see `init-editing-utils.el`: `display-fill-column-indicator-character` is set to a unicode character that appears to be missing in your font. You can either change that code, or try a different font, but I can't offer advice for Emacs on Windows sorry.

**Comment by gwijayas** [comment] 2023-12-27 03:42
@kungelee try download [this](https://ftp.gnu.org/gnu/emacs/windows/emacs-29/emacs-29.1_2.zip) instead. I think, your emacs build, not support tree-sitter (the message: cannot activate tree-sitter. After running emacs, try <kbd>Ctrl</kbd> + <kbd>h</kbd> and put `treesit-extra-load-path`. if is supported, the message buffer will like `treesit-extra-load-path is a variable defined in ‘C source code’.` (I tested from [zip version](https://ftp.gnu.org/gnu/emacs/windows/emacs-29/emacs-29.1_2.zip) and [exe](https://ftp.gnu.org/gnu/emacs/windows/emacs-29/emacs-29.1_2-installer.exe) running on Windows 10

As for me, I have succesfully build emacs 29.1 with tree-sitter supported, on windows using [this recipe](https://gist.github.com/nauhygon/f3b44f51b34e89bc54f8)

**Comment by purcell** [comment] 2023-12-27 07:19
Closing as the issue is resolved in this repo.

**Closed by purcell** 2023-12-27 07:19 UTC
